name: GitHub Action Test Run

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - dev
          - qa

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # setup
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      # clean test
      - name: Clean tests result
        run: ./gradlew clean

      # run tests
      - name: Run tests
        continue-on-error: true
        run: env=${{ inputs.environment }} ./gradlew test --tests "org.example.suites.RegressionSuite"

      # allure check
      - name: Check if Allure is installed
        run: |
          if ! command -v allure &> /dev/null
          then
           sudo apt-add-repository ppa:qameta/allure
           sudo apt-get update 
           sudo apt-get install allure
          fi

      # allure report
      - name: Generate Allure report
        run: |
          allure generate --results-dir build/allure-results --report-dir build/allure-report

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: build/allure-report
